"""empty message

Revision ID: 026ca9013d0d
Revises: 36bd65f2d898
Create Date: 2020-07-20 21:36:46.476613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '026ca9013d0d'
down_revision = '36bd65f2d898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('user', sa.Column('date_register', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('section_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('user', sa.Column('subject_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_foreign_key(None, 'user', 'subject', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'user', 'section', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'subject_id')
    op.drop_column('user', 'section_id')
    op.drop_column('user', 'email')
    op.drop_column('user', 'date_register')
    op.drop_table('subject')
    op.drop_table('section')
    # ### end Alembic commands ###
