"""empty message

Revision ID: 058063dffc44
Revises: b5fa89e6f120
Create Date: 2020-06-09 12:10:16.380071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '058063dffc44'
down_revision = 'b5fa89e6f120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_student_number_key', 'student', type_='unique')
    op.drop_column('student', 'student_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('student_number', postgresql.INT8RANGE(), autoincrement=False, nullable=False))
    op.create_unique_constraint('student_student_number_key', 'student', ['student_number'])
    # ### end Alembic commands ###
