"""empty message

Revision ID: 0e22c09284d6
Revises: 83dca3203e43
Create Date: 2020-06-16 16:53:45.168448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e22c09284d6'
down_revision = '83dca3203e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userRole', sa.Column('role_name', sa.String(length=20), nullable=True))
    op.drop_constraint('userRole_role_id_fkey', 'userRole', type_='foreignkey')
    op.create_foreign_key(None, 'userRole', 'role', ['role_name'], ['name'], ondelete='CASCADE')
    op.drop_column('userRole', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userRole', sa.Column('role_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'userRole', type_='foreignkey')
    op.create_foreign_key('userRole_role_id_fkey', 'userRole', 'role', ['role_id'], ['name'], ondelete='CASCADE')
    op.drop_column('userRole', 'role_name')
    # ### end Alembic commands ###
