"""empty message

Revision ID: 3959856a6701
Revises: 66e2411ea6e3
Create Date: 2020-07-20 23:41:34.308310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3959856a6701'
down_revision = '66e2411ea6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('area', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('category', 'code',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('keyword', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('program', 'code',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('program', 'college',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.add_column('section', sa.Column('code', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'section', ['code'])
    op.alter_column('semester', 'code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subject', 'code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('subject', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('thesis', 'category_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('thesis', 'program_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('thesis', 'research_area_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('thesis', 'school_year',
               existing_type=postgresql.INT4RANGE(),
               nullable=True)
    op.alter_column('thesis', 'semester_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('user', 'date_register',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'date_register',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('thesis', 'semester_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('thesis', 'school_year',
               existing_type=postgresql.INT4RANGE(),
               nullable=True)
    op.alter_column('thesis', 'research_area_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('thesis', 'program_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('thesis', 'category_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('subject', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('subject', 'code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('semester', 'code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'section', type_='unique')
    op.drop_column('section', 'code')
    op.alter_column('program', 'college',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('program', 'code',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('keyword', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('category', 'code',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('area', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
