"""empty message

Revision ID: 46606b24b446
Revises: 958eac2cbc58
Create Date: 2020-08-04 21:32:16.083746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46606b24b446'
down_revision = '958eac2cbc58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thesis', 'form_file',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('thesis', 'thesis_file',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thesis', 'thesis_file',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('thesis', 'form_file',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
