"""empty message

Revision ID: 50d5466f81c6
Revises: f42a81587892
Create Date: 2020-06-16 17:25:38.698613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50d5466f81c6'
down_revision = 'f42a81587892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userRole')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='role_pkey'),
    sa.UniqueConstraint('name', name='role_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('middle_initial', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('suffix', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('image_file', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('username', name='user_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('userRole',
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('role_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_name'], ['role.name'], name='userRole_role_name_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='userRole_user_id_fkey', ondelete='CASCADE')
    )
    # ### end Alembic commands ###
