"""empty message

Revision ID: 5383fa3a510c
Revises: d5f62ab6ee69
Create Date: 2020-12-02 20:02:30.399547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5383fa3a510c'
down_revision = 'd5f62ab6ee69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('http_error', mysql.SMALLINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'http_error')
    # ### end Alembic commands ###
