"""empty message

Revision ID: 53ebd4ced8e6
Revises: 3b2ad3efd53c
Create Date: 2020-06-16 21:13:13.700563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ebd4ced8e6'
down_revision = '3b2ad3efd53c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'program', ['id'])
    op.create_unique_constraint(None, 'thesis', ['id'])
    op.alter_column('thesisstatus', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_unique_constraint(None, 'thesisstatus', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thesisstatus', type_='unique')
    op.alter_column('thesisstatus', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_constraint(None, 'thesis', type_='unique')
    op.drop_constraint(None, 'program', type_='unique')
    # ### end Alembic commands ###
