"""empty message

Revision ID: 612a6e603852
Revises: 6a12d522f659
Create Date: 2020-07-20 19:36:56.700010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612a6e603852'
down_revision = '6a12d522f659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('surnamelmao', sa.String(length=40), nullable=True))
    op.drop_column('user', 'surname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('surname', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_column('user', 'surnamelmao')
    # ### end Alembic commands ###
