"""empty message

Revision ID: 6a12d522f659
Revises: 86f58dd5c3ec
Create Date: 2020-07-12 19:37:26.985340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a12d522f659'
down_revision = '86f58dd5c3ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test', sa.VARCHAR(length=29), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
