"""empty message

Revision ID: 7c9bb7cc6765
Revises: 612a6e603852
Create Date: 2020-07-20 19:47:32.497086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9bb7cc6765'
down_revision = '612a6e603852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'middle_initial')
    op.drop_column('user', 'firstname')
    op.drop_column('user', 'surnamelmao')
    op.drop_column('user', 'suffix')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('suffix', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('surnamelmao', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('firstname', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('middle_initial', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
