"""empty message

Revision ID: 8357c28cbda4
Revises: 883d927d0a9e
Create Date: 2020-06-14 21:30:59.078190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8357c28cbda4'
down_revision = '883d927d0a9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('college_program', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='program_pkey'),
    sa.UniqueConstraint('college_program', name='program_college_program_key'),
    sa.UniqueConstraint('id', name='program_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('thesis',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('program', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('date_deploy', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_input', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('semester', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('adviser', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('thesis_file', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('call_number', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['program'], ['program.college_program'], name='thesis_program_fkey'),
    sa.PrimaryKeyConstraint('id', name='thesis_pkey'),
    sa.UniqueConstraint('call_number', name='thesis_call_number_key'),
    sa.UniqueConstraint('id', name='thesis_id_key'),
    sa.UniqueConstraint('title', name='thesis_title_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('student',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('thesis', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('student_number', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['thesis'], ['thesis.title'], name='student_thesis_fkey'),
    sa.PrimaryKeyConstraint('id', name='student_pkey'),
    sa.UniqueConstraint('id', name='student_id_key'),
    sa.UniqueConstraint('name', name='student_name_key'),
    sa.UniqueConstraint('student_number', name='student_student_number_key')
    )
    # ### end Alembic commands ###
