"""empty message

Revision ID: 86f58dd5c3ec
Revises: dfe57e3afeb0
Create Date: 2020-07-12 19:36:27.923170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f58dd5c3ec'
down_revision = 'dfe57e3afeb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'test',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=29),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'test',
               existing_type=sa.String(length=29),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
