"""empty message

Revision ID: 883d927d0a9e
Revises: 058063dffc44
Create Date: 2020-06-09 12:11:22.911293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883d927d0a9e'
down_revision = '058063dffc44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('student_number', sa.BIGINT(), nullable=False))
    op.create_unique_constraint(None, 'student', ['student_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_column('student', 'student_number')
    # ### end Alembic commands ###
