"""empty message

Revision ID: 8a993dee26a7
Revises: b61c5bdc22cf
Create Date: 2020-07-20 19:56:13.126838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a993dee26a7'
down_revision = 'b61c5bdc22cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thesis_contributors',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('thesis_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    op.drop_table('thesisContributors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thesisContributors',
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('thesis_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], name='thesisContributors_thesis_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='thesisContributors_user_id_fkey', ondelete='CASCADE')
    )
    op.drop_table('thesis_contributors')
    # ### end Alembic commands ###
