"""empty message

Revision ID: 8fef8c9c227e
Revises: 3b7c6fb22949
Create Date: 2020-07-20 22:49:44.881746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fef8c9c227e'
down_revision = '3b7c6fb22949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('college', sa.String(length=30), nullable=True),
    sa.Column('code', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('college'),
    sa.UniqueConstraint('id')
    )
    op.alter_column('area', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_unique_constraint(None, 'area', ['id'])
    op.alter_column('category', 'code',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_unique_constraint(None, 'category', ['id'])
    op.alter_column('keyword', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_unique_constraint(None, 'keyword', ['id'])
    op.alter_column('section', 'code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('semester', 'code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'semester', ['id'])
    op.alter_column('subject', 'code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('subject', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.add_column('thesis', sa.Column('program_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.alter_column('thesis', 'category_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('thesis', 'research_area_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('thesis', 'school_year',
               existing_type=postgresql.INT4RANGE(),
               nullable=True)
    op.alter_column('thesis', 'semester_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'thesis', 'program', ['program_id'], ['id'])
    op.alter_column('user', 'date_register',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'date_register',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'thesis', type_='foreignkey')
    op.alter_column('thesis', 'semester_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('thesis', 'school_year',
               existing_type=postgresql.INT4RANGE(),
               nullable=True)
    op.alter_column('thesis', 'research_area_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('thesis', 'category_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_column('thesis', 'program_id')
    op.alter_column('subject', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('subject', 'code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_constraint(None, 'semester', type_='unique')
    op.alter_column('semester', 'code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('section', 'code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_constraint(None, 'keyword', type_='unique')
    op.alter_column('keyword', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(None, 'category', type_='unique')
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('category', 'code',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.drop_constraint(None, 'area', type_='unique')
    op.alter_column('area', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_table('program')
    # ### end Alembic commands ###
