"""empty message

Revision ID: 958eac2cbc58
Revises: 3053b3aa3718
Create Date: 2020-08-02 18:13:36.174954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958eac2cbc58'
down_revision = '3053b3aa3718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'thesis', ['thesis_file'])
    op.create_unique_constraint(None, 'thesis', ['form_file'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thesis', type_='unique')
    op.drop_constraint(None, 'thesis', type_='unique')
    # ### end Alembic commands ###
