"""empty message

Revision ID: 96f8ca59cf09
Revises: f6a2e5058e80
Create Date: 2020-06-09 11:43:09.882626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96f8ca59cf09'
down_revision = 'f6a2e5058e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'program', ['id'])
    op.drop_constraint('student_student_number_key', 'student', type_='unique')
    op.create_unique_constraint(None, 'student', ['id'])
    op.drop_column('student', 'student_number')
    op.create_unique_constraint(None, 'thesis', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thesis', type_='unique')
    op.add_column('student', sa.Column('student_number', postgresql.INT8RANGE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student', type_='unique')
    op.create_unique_constraint('student_student_number_key', 'student', ['student_number'])
    op.drop_constraint(None, 'program', type_='unique')
    # ### end Alembic commands ###
