"""empty message

Revision ID: 99ed72e23d8c
Revises: 
Create Date: 2020-11-30 23:38:58.240348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99ed72e23d8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('college')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('thesis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('sy_start', mysql.YEAR(), nullable=False),
    sa.Column('sy_end', mysql.YEAR(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('research_area_id', sa.Integer(), nullable=False),
    sa.Column('form_file', sa.String(length=30), nullable=True),
    sa.Column('thesis_file', sa.String(length=30), nullable=True),
    sa.Column('date_deploy', sa.DateTime(), nullable=True),
    sa.Column('date_register', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['research_area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_number'),
    sa.UniqueConstraint('form_file'),
    sa.UniqueConstraint('thesis_file'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=11), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('middle_initial', sa.String(length=5), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('date_register', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('thesis_contributors',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('thesis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    op.create_table('thesis_keywords',
    sa.Column('thesis_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], ondelete='CASCADE')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('thesis_keywords')
    op.drop_table('thesis_contributors')
    op.drop_table('user')
    op.drop_table('thesis')
    op.drop_table('subject')
    op.drop_table('semester')
    op.drop_table('section')
    op.drop_table('role')
    op.drop_table('program')
    op.drop_table('keyword')
    op.drop_table('category')
    op.drop_table('area')
    # ### end Alembic commands ###
