"""empty message

Revision ID: b5fa89e6f120
Revises: 96f8ca59cf09
Create Date: 2020-06-09 11:45:08.212880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5fa89e6f120'
down_revision = '96f8ca59cf09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('student_number', postgresql.INT8RANGE(), nullable=False))
    op.create_unique_constraint(None, 'student', ['student_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_column('student', 'student_number')
    # ### end Alembic commands ###
