"""empty message

Revision ID: b61c5bdc22cf
Revises: 7c9bb7cc6765
Create Date: 2020-07-20 19:51:39.498013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b61c5bdc22cf'
down_revision = '7c9bb7cc6765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thesis', sa.Column('date_register', sa.DateTime(), nullable=False))
    op.add_column('thesis', sa.Column('form_file', sa.String(length=20), nullable=True))
    op.drop_column('thesis', 'date_input')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thesis', sa.Column('date_input', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('thesis', 'form_file')
    op.drop_column('thesis', 'date_register')
    # ### end Alembic commands ###
