"""empty message

Revision ID: e1d04efc9281
Revises: 46606b24b446
Create Date: 2020-09-09 20:29:49.125370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d04efc9281'
down_revision = '46606b24b446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('middle_initial', sa.String(length=5), nullable=True))
    op.execute("UPDATE public.user SET first_name = 'NONE'")
    op.alter_column('user', 'first_name', nullable=False)
    op.execute("UPDATE public.user SET last_name = 'NONE'")
    op.alter_column('user', 'last_name', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'middle_initial')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
